# Site Settings
minimal_mistakes_skin: "default"
locale: "pt-BR"
title: "Programming with Kvojps"
title_separator: "|"
subtitle: "yet another coding blog"
name: "José Ferreira dos Santos Júnior"
description: "Yet another coding blog..."
url: https://kvojps.github.io/learn-programming/
repository: "kvojps/learn-programming"
words_per_minute: 160
search: true
search_full_content: true

# Site Author
author:
  name: "José Ferreira"
  bio: "Just a programmer wanting to share knowledge"
  location: "Pernambuco, Brazil"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kvojps"

# Site Footer
footer:
  - label: "GitHub"
    icon: "fab fa-fw fa-github"
    url: "https://github.com/kvojps"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: America/Recife

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      toc_sticky: true
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _funcional
  - scope:
      path: ""
      type: funcional
    values:
      toc_sticky: true
      author_profile: true
      layout: single
      share: true
      related: true
      read_time: true

collections:
  funcional:
    output: true
    permalink: /:collection/:path
    #sort_by: lesson
  tags:
    output: true
    permalink: tags/:path/
